### PR TITLE
Please review my codes

### PR DESCRIPTION
**Pull request by MohammedAlshalchi**
Good afternoon terrfic team PLS review my codes

### CODE REVIEW

**Review by TamerlanHuseynov — APPROVED** [review]
I approve the merge request but I am gonna delete DataProvider intrerface because it does not contain anything

**Comment by MohammedAlshalchi** [comment]
ok , that looks great
thanks for reviewing my codes

‫في الثلاثاء، 15 مارس 2022 في 8:32 م تمت كتابة ما يلي بواسطة ‪Tamerlan‬‏ <‪
***@***.***‬‏>:‬

**Review by yasamanibr — APPROVED** [review]
Approved.

**Comment by yasamanibr** [comment]
Well done.

**Pull request closed without merging**
