### PR TITLE
US_64_Zhyldyz

### PR DESCRIPTION
**Pull request by ZhyldyzAmanova**

### CODE REVIEW

**Review by KatiU — APPROVED** [review]
good job!

**Review by olesiasokol — APPROVED** [review]
Great work!

**Review by TamerlanHuseynov — APPROVED** [review]
Applouds!

**Review by TamerlanHuseynov — CHANGES_REQUESTED** [review]
Do not add new Test Base class

**Review by TamerlanHuseynov — APPROVED** [review]
Cool!

**Review by olesiasokol — APPROVED** [review]
Great work!

**Pull request merged**
